ARG IMAGE_PREFIX=ilbumi/python-toolkit
ARG VERSION=UNKNOWN
ARG MAMBA_DOCKERFILE_ACTIVATE=1

FROM ${IMAGE_PREFIX}:${VERSION}-devbase

COPY --chown=$MAMBA_USER:$MAMBA_USER environments/pytorch.yaml /tmp/env.yaml
ARG MAMBA_DOCKERFILE_ACTIVATE=1
RUN --mount=type=cache,target=/opt/conda/pkgs \
    micromamba install -y \
    --file /tmp/env.yaml

EXPOSE 8888
WORKDIR /home/mambauser