ARG IMAGE_PREFIX=ilbumi/python-toolkit
ARG VERSION=UNKNOWN
ARG BASE_IMAGE=$(IMAGE_PREFIX):$(VERSION)-base

FROM ${BASE_IMAGE}

COPY --chown=$MAMBA_USER:$MAMBA_USER environments/base.yaml /tmp/base.yaml
COPY --chown=$MAMBA_USER:$MAMBA_USER environments/pytorch.yaml /tmp/pytorch.yaml
ARG MAMBA_DOCKERFILE_ACTIVATE=1
RUN --mount=type=cache,target=/opt/conda/pkgs \
    micromamba install -y \
    --file /tmp/base.yaml \
    --file /tmp/pytorch.yaml

EXPOSE 8888
WORKDIR /home/mambauser/data